force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>It is responsible to transfer the logs asynchronously</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/ComponentName__c.field-meta.xml
<CustomField>
    <fullName>ComponentName__c</fullName>
    <description>It contains the component name, where the event occurred.</description>
    <label>ComponentName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ComponentType__c.field-meta.xml
<CustomField>
    <fullName>ComponentType__c</fullName>
    <description>It contains the component type, which generated this log, it could be apex class, trigger, LWC, Aura, Flow etc..</description>
    <label>Component Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <description>It contains the feature accessed by the user</description>
    <label>Feature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>LoggingLevel__c</fullName>
    <description>contains the logging level i.e. fine, debug, info, warn, error</description>
    <label>LoggingLevel</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>contains the message to print</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>id of the user, performing the actions</description>
    <label>User Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LoggingConfigurations__c/fields/LoggingEnabled__c.field-meta.xml
<CustomField>
    <fullName>LoggingEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to enable/disable the log</description>
    <label>Logging Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LoggingConfigurations__c/fields/LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>LoggingLevel__c</fullName>
    <description>contains the active log level</description>
    <label>Logging Level</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AbstractLogger.cls
/**
* @name: AbstractLogger
* @description: abstract class for logging
* @author: Gagandeep Bansal
* @date: 10/02/2024
* @group Logging Framework   
*/
public abstract class AbstractLogger { 

    private static final String DEFAULT_LOGGING_LEVEL_KEY   = 'Default';

    
    //to store custom settings
    private boolean isLoggingEnabled = false; 
    private LoggingLevel defaultLoggingLevel;
    
    /*
    *    LoggingLevel    ordinal 
    *       NONE            0
    *       INTERNAL        1
    *       FINEST          2
    *       FINER           3
    *       FINE            4
    *       DEBUG           5
    *       INFO            6
    *       WARN            7
    *       ERROR           8
    */

    private void populateLoggingConfigurations () {
        List<LoggingConfigurations__c > logConfSettings = [SELECT LoggingLevel__c, LoggingEnabled__c  FROM LoggingConfigurations__c];
        if (logConfSettings.size() > 0) {
                this.isLoggingEnabled                     = logConfSettings[0].LoggingEnabled__c;
                this.defaultLoggingLevel                  = LoggingLevel.NONE;
               
                for (LoggingLevel systemLoggingLevel : LoggingLevel.values()) {
                    if (systemLoggingLevel.name() == logConfSettings[0].LoggingLevel__c) {
                        this.defaultLoggingLevel = systemLoggingLevel;
                        break;
                    }
                }                         
             
        } 
    }
    
    protected void log (LoggingLevel logLevel, String feature, String componentType, String componentName, String message) {
        populateLoggingConfigurations(); 
        
        if (!this.isLoggingEnabled) {
            return;
        }
        
        if (LoggingLevel.NONE == this.defaultLoggingLevel) {
            return;
        }
        
        if (this.defaultLoggingLevel.ordinal() <= logLevel.ordinal()) {
            LogEvent__e logEvent = createLogEvent(feature, componentType, componentName, logLevel.name(), message);
            publishLogEvent(logEvent);
        }   
    }

    
    private LogEvent__e createLogEvent (String feature, String componentType, String componentName, String loggingLevel, String message) {
        
        LogEvent__e event = new LogEvent__e(
            ComponentType__c     		= componentType,
            ComponentName__c     		= componentName,
            Feature__c 					= feature,
            LoggingLevel__c    			= loggingLevel,
            Message__c          		= message == null ? null : String.valueOf(message),
            UserId__c  					= UserInfo.getUserId()
        );
        return event;
    }

    private void publishLogEvent (LogEvent__e logEvent) {
        try {
            EventBus.publish(logEvent);
        } catch (DMLException ex) {
            System.debug ('Error while logging : ' + ex.getMessage()); 
        }
    }
}