force-app/main/default/objects/CommonLog__c/CommonLog__c.object-meta.xml
<CustomObject>
    <description>It contains the application logs of the activities performed by the user</description>
    <label>Common Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Common Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommonLog__c/fields/ComponentName__c.field-meta.xml
<CustomField>
    <fullName>ComponentName__c</fullName>
    <description>It contains the component name, where the event occurred.</description>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommonLog__c/fields/ComponentType__c.field-meta.xml
<CustomField>
    <fullName>ComponentType__c</fullName>
    <description>It contains the component type, which generated this log, it could be apex class, trigger, LWC, Aura, Flow etc..</description>
    <label>Component Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommonLog__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <description>It contains the feature accessed by the user</description>
    <label>Feature</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Web Order</fullName>
            </value>
            <value>
                <fullName>Web Lead</fullName>
            </value>
            <value>
                <fullName>Net Price Enhanced</fullName>
            </value>
            <value>
                <fullName>ARC Tool</fullName>
            </value>
            <value>
                <fullName>Price Analysis Tool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommonLog__c/fields/LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>LoggingLevel__c</fullName>
    <description>contains the logging level i.e. fine, debug, info, warn, error</description>
    <label>Logging Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fine</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warn</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommonLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>contains the message to print</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CommonLog__c/fields/SessionId__c.field-meta.xml
<CustomField>
    <fullName>SessionId__c</fullName>
    <description>It contains the user session id, which is performing the event</description>
    <label>Session Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>It is responsible to transfer the logs asynchronously</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogEvent__e/fields/ComponentName__c.field-meta.xml
<CustomField>
    <fullName>ComponentName__c</fullName>
    <description>It contains the component name, where the event occurred.</description>
    <label>ComponentName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/ComponentType__c.field-meta.xml
<CustomField>
    <fullName>ComponentType__c</fullName>
    <description>It contains the component type, which generated this log, it could be apex class, trigger, LWC, Aura, Flow etc..</description>
    <label>Component Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <description>It contains the feature accessed by the user</description>
    <label>Feature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>LoggingLevel__c</fullName>
    <description>contains the logging level i.e. fine, debug, info, warn, error</description>
    <label>LoggingLevel</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>contains the message to print</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/SessionId__c.field-meta.xml
<CustomField>
    <fullName>SessionId__c</fullName>
    <description>It contains the user session id, which is performing the event</description>
    <label>Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>id of the user, performing the actions</description>
    <label>User Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoggingEventTriggerHandler.cls
public without sharing class LoggingEventTriggerHandler implements ITriggerHandler {
    public static Boolean TriggerDisabled = false;

    public Boolean isDisabled() {
        return TriggerDisabled;
    }
    
    public void beforeInsert(List<sObject> newList) {}

    public void afterInsert(List<LogEvent__e> logEvents, Map<Id, sObject> newMap) {
        List<CommonLog__c> commonLogs = new List<CommonLog__c>();
    
        for (LogEvent__e logEvent : logEvents) {
            CommonLog__c commonLog = new CommonLog__c(
                ComponentType__c    = logEvent.ComponentType__c,
                ComponentName__c    = logEvent.ComponentName__c,
                LoggingLevel__c     = logEvent.LoggingLevel__c,
                OwnerId   			= logEvent.UserId__c,   
                Message__c          = logEvent.Message__c,
                Feature__c     		= logEvent.Feature__c ,
                SessionId__c        = logEvent.SessionId__c 
      		);
            
          commonLogs.add(commonLog);
        }
        insert commonLogs;
    }
    
    public void beforeUpdate(List<sObject> newList, Map<Id, sObject> newMap,  List<sObject> oldList, Map<Id, sObject> oldMap) {}

    public void afterUpdate(List<sObject> newList, Map<Id, sObject> newMap, List<sObject> oldList, Map<Id, sObject> oldMap) {}

    public void beforeDelete(List<sObject> oldList , Map<Id, sObject> oldMap) {}

    public void afterDelete(List<sObject> oldList , Map<Id, sObject> oldMap) {}

    public void afterUnDelete(List<sObject> newList, Map<Id, sObject> newMap) {}
}